spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LegajosMS
    username: postgres
    password: support219
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update